apiVersion: database.aws.crossplane.io/v1beta1
kind: DBSubnetGroup
metadata:
  name: Dev-subnet-group
spec:
  forProvider:
    region: us-east-1
    description: "Dev Subnet group"
    subnetIdRefs:
      - name: test-subnet-2
      - name: test-subnet-1
  providerConfigRef:
    name: awsconfig

--- 

apiVersion: database.aws.crossplane.io/v1beta1
kind: RDSInstance
metadata:
  name: Dev-rds
spec:
  forProvider:
    allocatedStorage: 20
    autoMinorVersionUpgrade: true
    applyModificationsImmediately: false
    backupRetentionPeriod: 0
    caCertificateIdentifier: rds-ca-2019
    copyTagsToSnapshot: false
    dbInstanceClass: db.t2.small
    dbSubnetGroupName: prod-subnet-group 
    vpcSecurityGroupIDRefs:
      name: rds-access-sg
    deletionProtection: false
    enableIAMDatabaseAuthentication: false
    enablePerformanceInsights: false
    engine: mysql
    region: us-east-1
    engineVersion: 5.6.35
    finalDBSnapshotIdentifier: muvaf-test
    licenseModel: general-public-license
    masterUsername: admin
    multiAZ: true
    port: 3306
    tags:
    - key: Name
      value: Dev-rds
    - key: Environment
      value: Dev
    - key: Owner
      value: Selvam
    publiclyAccessible: true
    storageEncrypted: false
    storageType: gp2
  providerConfigRef:
    name: awsconfig
  writeConnectionSecretToRef:
    name: Dev-rds-conn-string
    namespace: default
